---
title: "3-6 yrs old"
author: "Kaiwen"
date: "2024-02-28"
output: pdf_document
---

# 0. Packages Library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# r package library
library(papaja)
library(tidyverse)
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(childesr)
```

```{r data-function}
get_filtered_utterances <- function(role, age, corpus) {

  utterances <- get_utterances(role = role, age = age, corpus = corpus)
  
  filtered_utterances <- select(utterances, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)
  
  return(filtered_utterances)
}

```

# 1. Dataset: 

```{r data-selection}
## 1.1 Warren Corpus, 10 children
warren <- get_filtered_utterances(role = "Mother", age = c(36,72), corpus = "Warren")

## 1.2 Weist Corpus, 6 children (3 girls, 3 boys)
weist <- get_filtered_utterances(role = "Mother", age = c(36,72), corpus = "Weist")

## 1.3 Sachs Corpus, 1 child (1 girl)
sachs <- get_filtered_utterances(role = "Mother", age = c(36,72), corpus = "Sachs")

## 1.4 Gleason Corpus
gleason <- get_filtered_utterances(role = "Mother", age = c(36,72), corpus = "Gleason")
```

# 2. Combine all data

```{r combine-dataset}
combined_36 <- bind_rows(gleason, warren, sachs, weist)

## 2.1 filter utterances that include adj.
adj_36 <- combined_36 %>% 
  filter(grepl("adj", part_of_speech))

## 2.2 filter utterances that include nouns.
noun_36 <- combined_36 %>% 
  filter(grepl("n", part_of_speech))
```

# 3. Filter target utts
```{r filter-utts}
# Filter gloss that contains the specified Gender-Biased Nouns
# 1. male-biased nouns
mnoun_words <- c("broom", "firetruck", "truck", "train", "hammer", "motorcycle", "shovel")
mnoun36 <- noun_36 %>% 
  filter(sapply(mnoun_words, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

mnoun36_number <- mnoun36 %>%
  group_by(target_child_name) %>%
  summarise(mnoun_count = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_mnoun_number, by = "target_child_name")

# 2. female-biased nouns
fnoun_words <- c("dress", "doll", "necklace", "purse", "baby", "sweater", "girl")
pro_fnoun <- pro_utterance %>% 
  filter(sapply(fnoun_words, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_fnoun_number <- pro_fnoun %>%
  group_by(target_child_name) %>%
  summarise(fnoun_count = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_fnoun_number, by = "target_child_name")

# Filter gloss that contains Competence-related adj.s
com_adj <- c("clever","brilliant","smart","strong")
pro_com <- pro_utterance %>% 
  filter(sapply(com_adj, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_com_number <- pro_com %>%
  group_by(target_child_name) %>%
  summarise(competence_adj_number = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_com_number, by = "target_child_name")
write_csv(pro_utterance_number, "/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Providence Example/Providence_utt_num.csv")

```


