---
title: "Providence_example"
author: "Kaiwen"
date: "2024-02-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# r package library
library(papaja)
library(tidyverse)
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(childesr)
```

# 4. Providence Example

## 4.1 Adj

```{r providence-adj}
appearance_words <- c("handsome", "gorgeous", "beautiful", "lovely", "cute")

# Filter gloss that contains the appearance-related adj.s
pro_appearance <- pro_utterance %>% 
  filter(sapply(appearance_words, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_adj_number <- pro_appearance %>%
  group_by(target_child_name) %>%
  summarise(adj_appearance_no_pretty = n())

pro_utterance_number <- pro_utterance %>%
  group_by(target_child_name) %>%
  summarise(utterance_count = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_adj_number, by = "target_child_name")

print(pro_utterance_number)
```

## 4.2 Nouns

```{r providence-nouns}
# Filter gloss that contains the specified Gender-Biased Nouns
# 1. male-biased nouns
mnoun_words <- c("broom", "firetruck", "truck", "train", "hammer", "motorcycle", "shovel")
pro_mnoun <- pro_utterance %>% 
  filter(sapply(mnoun_words, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_mnoun_number <- pro_mnoun %>%
  group_by(target_child_name) %>%
  summarise(mnoun_count = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_mnoun_number, by = "target_child_name")

# 2. female-biased nouns
fnoun_words <- c("dress", "doll", "necklace", "purse", "baby", "sweater", "girl")
pro_fnoun <- pro_utterance %>% 
  filter(sapply(fnoun_words, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_fnoun_number <- pro_fnoun %>%
  group_by(target_child_name) %>%
  summarise(fnoun_count = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_fnoun_number, by = "target_child_name")

# Filter gloss that contains Competence-related adj.s
com_adj <- c("clever","brilliant","smart","strong")
pro_com <- pro_utterance %>% 
  filter(sapply(com_adj, function(word) grepl(word, gloss, ignore.case = TRUE)) %>% rowSums() > 0)

pro_com_number <- pro_com %>%
  group_by(target_child_name) %>%
  summarise(competence_adj_number = n())

pro_utterance_number <- left_join(pro_utterance_number, pro_com_number, by = "target_child_name")
print(pro_utterance_number)
```

## 4.3 Combined

```{r combine-data}
# Calculate proportion and add it to the dataframe
pro_proportion <- pro_utterance_number %>%
  mutate(mnoun_proportion = mnoun_count / utterance_count) %>%
  mutate(fnoun_proportion = fnoun_count / utterance_count) %>%
  mutate(app_adj_proportion = adj_appearance_no_pretty / utterance_count) %>%
  mutate(com_adj_proportion = competence_adj_number / utterance_count)
print(pro_proportion)

print(pro_proportion)
```

## 4.4 Plot

```{r providence-plot}
pro_proportion <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Providence Example/Providence_Proportion.csv")

# Gender-biased Nouns Plot
long_pro_noun <- pro_proportion %>%
  pivot_longer(cols = c(mnoun_proportion, fnoun_proportion),
               names_to = "type",
               values_to = "proportion")
labels_gender = c('fnoun_proportion' = "Female-Biased", 'mnoun_proportion' = "Male-Biased")

plot_pro_noun <- ggplot(long_pro_noun, aes(x = target_child_sex, y = proportion, fill = target_child_sex)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(alpha = 0.7, aes(colour = target_child_sex)) +
  scale_fill_manual(values = c("female" = "lightpink", "male" = "lightblue")) +
  labs(x = "Gender", y = "Proportion") +
  facet_wrap(~type, scales = "fixed", labeller = as_labeller(labels_gender)) +
  labs(title = "Providence Corpus: Proportion of Gender-Biased Nouns")+
  theme(
    panel.grid = element_line(colour = "white", linetype = 3, size = .7),
    legend.title = element_text(size = 10),
    strip.background = element_rect(fill = "gray60"),
    strip.text = element_text(colour = "white", hjust = 0),
    legend.position = "bottom"
  )
 print(plot_pro_noun)
 
 # Gender-biased Adj.s 
 long_pro_adj <- pro_proportion %>%
   pivot_longer(cols = c(app_adj_proportion, com_adj_proportion),
                names_to = "type",
                values_to = "proportion")
 labels_gender_adj = c('app_adj_proportion' = "Appearance", 'com_adj_proportion' = "Competence")
 
 plot_pro_adj <- ggplot(long_pro_adj, aes(x = target_child_sex, y = proportion, fill = target_child_sex, colour = target_child_sex)) +
   geom_boxplot(alpha = 0.8) +
   scale_fill_manual(values = c("female" = "#F6BDDF", "male" = "#92CCCE")) +
   scale_color_manual(values = c("female" = "#CA69AF", "male" = "#337B9F")) + 
   geom_jitter(alpha = 0.7) + 
   labs(x = "Gender", y = "Proportion") +
   facet_wrap(~type, scales = "fixed", labeller = as_labeller(labels_gender_adj)) +
   labs(title = "Providence Corpus: Proportion of Biased Adj")+
   theme(
     panel.grid = element_line(colour = "white", linetype = 3, size = .7),
     legend.title = element_text(size = 10),
     strip.background = element_rect(fill = "gray60"),
     strip.text = element_text(colour = "white", family = "Courier", hjust = 0),
     legend.position = "bottom"
   )
print(plot_pro_adj)
```
