---
title: "Thesis data prep"
author: "Kaiwen"
date: "2024-02-14"
output: html_document
---

# 0. Packages Library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# r package library
library(papaja)
r_refs("r-references.bib")
library(tidyverse)
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(childesr)
```

# 1. Dataset: 6 Corpuses, 58 children

```{r data-selection}
## 1.1 Providence Corpus, 6 children (3 girls, 3 boys)
pro <- get_utterances(role = "Mother", age = c(12,36), corpus = "Providence")
pro_utterance <- select(pro, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)

## 1.2 Gleason Corpus, 7 children (3 girls, 4 boys)
### Laurel, Martin, Nanette, Patricia, Richard, Victor, William
gleason <- get_utterances(role = "Mother", age = c(12,36), corpus = "Gleason")
gle_utterance <- select(gleason, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)

## 1.3 McCune Corpus, 10 children
mcc <- get_utterances(role = "Mother", age = c(12,36), corpus = "McCune")
mcc_utterance <- select(mcc, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)

## 1.4 Warren Corpus, 9 children (4 girls, 5 boys)
warren <- get_utterances(role = "Mother", age = c(12,36), corpus = "Warren")
wr_utterance <- select(warren, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)

## 1.5 VanHouten Corpus, 20 children (8 girls, 12 boys)
van <- get_utterances(role = "Mother", age = c(12,36), corpus = "VanHouten")
van_utterance <- select(van, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)

## 1.6 Weist Corpus, 6 children (3 girls, 3 boys)
weist <- get_utterances(role = "Mother", age = c(12,36), corpus = "Weist")
wst_utterance <- select(weist, corpus_name, id, gloss, target_child_name, target_child_id, target_child_age, target_child_sex, part_of_speech, corpus_id, collection_id, speaker_id, transcript_id)
```

# 2. combine all data

```{r combine-dataset}

combined_utterance <- bind_rows(wst_utterance, van_utterance, wr_utterance,mcc_utterance, gle_utterance, pro_utterance)

## 2.1 filter utterances that include adj.
adj_utterance <- combined_utterance %>% 
  filter(grepl("adj", part_of_speech))

## 2.2 filter utterances that include nouns.
noun_utterance <- combined_utterance %>% 
  filter(grepl("n", part_of_speech))

## 2.3 export combined tibbles
#write.csv(adj_utterance, file = "/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/adj_utterance.csv", row.names = FALSE)
#write.csv(noun_utterance, file = "/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/noun_utterance.csv", row.names = FALSE)
```

# 3. Filter by gender

## 3.1 all utterances number

*Female biased nouns*: dress, doll, necklace, purse, baby, sweater, girl

```{r filter-by-gender, echo=FALSE}
adj_female <- adj_utterance %>% 
  filter(grepl("female", target_child_sex))
write.csv(adj_female, file = "adj_female.csv", row.names = FALSE)

table(adj_utterance$target_child_sex)

# female noun. utterance
n_female <- noun_utterance %>% 
  filter(grepl("female", target_child_sex))
write.csv(n_female, file = "n_female.csv", row.names = FALSE)

table(noun_utterance$target_child_sex)
## female noun. utterance:  98,396 obs.
##   male noun. utterance:  70,543 obs.

# check for NAs
which(is.na(adj_utterance$target_child_sex))
which(is.na(adj_utterance$target_child_name))

# what if the columns are blank??
adj_importNA <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/adj_utterance.csv", na = " ")

```

# 4. Plot

## 4.0 Plot-Function

```{r figure-function}
# noun plot
generate_noun_plot <- function(data_frame) {
  long_data_frame <- data_frame %>%
    pivot_longer(cols = c(mnoun_proportion, fnoun_proportion),
                 names_to = "type",
                 values_to = "proportion")
  
  labels_gender <- c('fnoun_proportion' = "Female-Biased", 'mnoun_proportion' = "Male-Biased")
  
  ggplot(long_data_frame, aes(x = target_child_sex, y = proportion, fill = target_child_sex)) +
    geom_boxplot(alpha = 0.5) +
    geom_jitter(alpha = 0.5, aes(colour = target_child_sex)) +
    scale_fill_manual(values = c("female" = "lightpink", "male" = "lightblue")) +
    labs(x = "Gender", y = "Proportion", fill = "Sex of Child", colour = "Sex of Child") +
    facet_wrap(~type, scales = "fixed", labeller = as_labeller(labels_gender)) +
    labs(title = "Proportion of Gender-Biased Nouns") +
    theme(
      legend.title = element_text(size = 10),
      strip.background = element_rect(fill = "gray60"),
      strip.text = element_text(colour = "white", hjust = 0),
      legend.position = "bottom"
    )
}

# adj plot
generate_adj_plot <- function(all_adj) {
  
  long_adj <- all_adj %>%
    pivot_longer(cols = c(without_pretty_proportion, com_proportion),
                 names_to = "type",
                 values_to = "proportion")
  
  labels_adj_gender <- c('without_pretty_proportion' = "Appearance", 'com_proportion' = "Competence")
  
  ggplot(long_adj, aes(x = target_child_sex, y = proportion, fill = target_child_sex)) +
    geom_boxplot(alpha = 0.5) +
    geom_jitter(alpha = 0.5, aes(colour = target_child_sex)) +
    scale_fill_manual(values = c("female" = "lightpink", "male" = "lightblue")) +
    labs(x = "Gender", y = "Proportion", fill = "Sex of Child", colour = "Sex of Child") +
    facet_wrap(~type, scales = "free_y", labeller = as_labeller(labels_adj_gender)) +
    labs(title = "Proportion of Biased Adjs") +
    theme(
      legend.title = element_text(size = 10),
      strip.background = element_rect(fill = "gray60"),
      strip.text = element_text(colour = "white", hjust = 0),
      legend.position = "bottom"
    )
}

```

## 4.1 Nouns

```{r nouns-figure, fig.cap="Proportion of Gender-Biased Nouns by Gender"}

combined.data <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Proportion data/noun_proportion_number.csv")

generate_noun_plot(combined.data)
```

## 4.2 Adj.s

```{r figure-adj, fig.cap="Proportion of Gender-Biased Adjs by Gender"}

all_adj <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Proportion data/all_adj_proportion.csv")

long_adj <- all_adj %>%
  pivot_longer(cols = c(without_pretty_proportion, com_proportion),
               names_to = "type",
               values_to = "proportion")
labels_adj_gender = c('without_pretty_proportion' = "Appearance", 'com_proportion' = "Competence")

ggplot(long_adj, aes(x = target_child_sex, y = proportion, fill = target_child_sex)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(alpha = 0.5, aes(colour = target_child_sex)) +
  scale_fill_manual(values = c("female" = "lightpink", "male" = "lightblue")) +
  labs(x = "Gender", y = "Proportion", fill = "Sex of Child", colour = "Sex of Child") +
  facet_wrap(~type, scales = "free_y", labeller = as_labeller(labels_adj_gender)) +
  labs(title = "Proportion of Biased Adjs")+
  theme(
  legend.title = element_text(size = 10),
  strip.background = element_rect(fill = "gray60"),
  strip.text = element_text(colour = "white", hjust = 0),
  legend.position = "bottom"
)
```

# 5. Count

## 5.1 All utterance count

Imported tidied table

```{r tidied-noun-count-table}
noun_tidied_count <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Proportion data/noun_proportion_number.csv")

adj_tidied_count <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/Proportion data/all_adj_proportion.csv")

print(noun_tidied_count)
print(adj_tidied_count)
```

## 5.2 Count \> 200

```{r count200, fig.cap = "utts > 200"}
noun_200 <- noun_tidied_count %>% filter(utt_count > 200)
adj_200 <- adj_tidied_count %>% filter(utt_count > 200)

generate_noun_plot(noun_200)
generate_adj_plot(adj_200)
```

## 5.3 Count \> 250

```{r count250}
noun_250 <- noun_tidied_count %>% filter(utt_count > 250)
adj_250 <- adj_tidied_count %>% filter(utt_count > 250)

generate_noun_plot(noun_250)
generate_adj_plot(adj_250)

```

## 5.4 Count \> 500

```{r count500}
noun_500 <- noun_tidied_count %>% filter(utt_count > 500)
adj_500 <- adj_tidied_count %>% filter(utt_count > 500)

generate_noun_plot(noun_500)
generate_adj_plot(adj_500)

```

#6. Pretty

```{r pretty-code}
pretty_table <- read.csv("/Users/katia/Desktop/D2M/CHILDES_utterance/Childes dataset/tidy data/Pretty.csv")

print(pretty_table)

```
